Repository decentraland/kernel, pull requests merged in 2019-11, with the labels that each got.

#625 fix: use take latest for corresponding user id in passport sagas
  packages/shared/passports/sagas.ts
  test/unit/passport.saga.test.tsx
Labels: bug, ready for review

#630 fix: multiplex sagas by user id when needed
  packages/shared/passports/sagas.ts
Labels: bug

#631 chore: parameterize engine path
  packages/entryPoints/editor.ts
  packages/unity-interface/initializer.ts
Labels: builder

#633 refactor: hud configuration
  packages/entryPoints/preview.ts
  packages/entryPoints/unity.ts
  packages/shared/types.ts
  packages/unity-interface/dcl.ts
Labels: do not merge, ready for review

#640 fix: builder don't need entity id when calling for deselection
  packages/entryPoints/editor.ts
  packages/unity-interface/dcl.ts
Labels: builder

#638 feat: disable client on login
  packages/shared/comms/index.ts
  packages/shared/comms/worldInstanceConnection.ts
  packages/shared/index.ts
  packages/shared/loading/ReportFatalError.ts
  packages/shared/loading/types.ts
  packages/shared/session/index.ts
  packages/shared/store/metricSaga.ts
  packages/unity-interface/dcl.ts
  packages/unity-interface/initializer.ts
  static/images/robotsmiling.png
  static/index.html
  static/styles/errors.css
Labels: ready for review
