Repository decentraland/kernel, pull requests merged in 2019-05, with the labels that each got.

#145 fix: update scenes
  packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json
  packages/decentraland-ecs/types/dcl/index.d.ts
  test/results/aframePrimitivesResult.0.png
  test/results/aframePrimitivesResult.1.png
  test/results/aframePrimitivesResult.2.png
  test/results/aframePrimitivesResult.3.png
  test/results/atlas.png
  test/results/avatar-fox.png
  test/results/avatar-profile-ui.png
  test/results/avatar-round-robot.png
  test/results/avatar-square-robot.png
  test/results/crocs.png
  test/results/gamekit-gltf.png
  test/results/gamekit-primitives.png
  test/results/inclusiveLimits.png
  test/results/lookAt.png
  test/results/material-billboard.png
  test/results/parcel-shape.png
  test/results/referenceSystem.3.png
  test/results/skyAndLights.0.png
  test/results/skyAndLights.1.png
  test/results/skyAndLights.2.png
  test/results/skyAndLights.3.png
  test/results/skyAndLights.4.png
  test/results/skyAndLights.5.png
  test/results/skyAndLights.6.png
  test/results/skyAndLights.7.png
  test/results/skyAndLights.8.png
  test/results/sun.png
  test/results/text.png
  test/results/transparent.2.png
  test/results/transparent.png
Labels: ready for review, tests

#141 feat: minor improvements to the minimap
  packages/decentraland-loader/src/utils.ts
  packages/engine/dcl/widgets/minimap.ts
  static/index.html
Labels: ready for review

#162 chore: update unity build to v0.2
  static/unity/Build/unity.data.unityweb
  static/unity/Build/unity.wasm.code.unityweb
  static/unity/Build/unity.wasm.framework.unityweb
  static/unity/game.js
Labels: ready for review

#165 chore: update new unity build to 0.3 version
  static/unity/Build/unity.data.unityweb
  static/unity/Build/unity.wasm.code.unityweb
  static/unity/Build/unity.wasm.framework.unityweb
Labels: ready for review

#169 feat: chain-ability of methods 2
  .vscode/settings.json
  packages/decentraland-ecs/src/decentraland/AnimationState.ts
  packages/decentraland-ecs/src/decentraland/Audio.ts
  packages/decentraland-ecs/src/decentraland/Components.ts
  packages/decentraland-ecs/src/decentraland/Input.ts
  packages/decentraland-ecs/src/ecs/Component.ts
  packages/decentraland-ecs/src/ecs/Engine.ts
  packages/decentraland-ecs/src/ecs/Entity.ts
  packages/decentraland-ecs/src/ecs/EventManager.ts
Labels: blocked

#179 fix: remove ice turn server config
  packages/config/index.ts
Labels: ready for review

#184 fix: add timestamp field to tracking events
  packages/shared/analytics.ts
Labels: analytics

#174 chore: reenable new scene lifecycle
  .gitignore
  build.sdk.json
  packages/decentraland-loader/README.md
  packages/decentraland-loader/lifecycle/controllers/download.ts
  packages/decentraland-loader/lifecycle/controllers/parcel.ts
  packages/decentraland-loader/lifecycle/controllers/position.ts
  packages/decentraland-loader/lifecycle/controllers/scene.ts
  packages/decentraland-loader/lifecycle/lib/adapter.ts
  packages/decentraland-loader/lifecycle/lib/parcel.status.ts
  packages/decentraland-loader/lifecycle/lib/scene.status.ts
  packages/decentraland-loader/lifecycle/lib/scope.ts
  packages/decentraland-loader/lifecycle/lib/types.ts
  packages/decentraland-loader/lifecycle/manager.ts
  packages/decentraland-loader/lifecycle/worker.ts
  packages/decentraland-loader/loader.system.ts
  packages/decentraland-loader/src/config.ts
  packages/decentraland-loader/src/landLoader.ts
  packages/decentraland-loader/src/parcelScene.ts
  packages/decentraland-loader/src/parcelSceneManager.ts
  packages/decentraland-loader/src/utils.ts
  packages/decentraland-loader/tsconfig.json
  packages/decentraland-loader/worker.ts
  packages/shared/types.ts
  packages/shared/world/parcelSceneManager.ts
  packages/unity-interface/dcl.ts
Labels: ready for review
