Repository decentraland/kernel, pull requests merged in 2019-09, with the labels that each got.

#430 feat: support global scene pointer events messaging
  packages/decentraland-ecs/src/decentraland/Events.ts
  packages/decentraland-ecs/src/decentraland/Implementation.ts
  packages/decentraland-ecs/src/decentraland/Input.ts
  packages/decentraland-ecs/src/decentraland/Systems.ts
  packages/decentraland-ecs/src/decentraland/Types.ts
  packages/decentraland-ecs/src/index.ts
  packages/engine/entities/SharedSceneContext.ts
  packages/unity-interface/dcl.ts
  public/test-scenes/-1.-50.basic-interactions/game.ts
Labels: merge me!

#455 fix: override entry points sources in tsconfig
  packages/entryPoints/tsconfig.json
Labels: bug, devexp/qa

#453 chore: temporally disable rollbar
  static/index.html
Labels: devexp/qa

#447 feat: cache scenes built on CircleCI based on the hash of decentraland-ecs
  .circleci/config.yml
  package-lock.json
  package.json
  packages/engine/index.ts
Labels: devexp/qa, ready for review

#458 chore: add scene boundaries test-scene
  public/test-scenes/0.90.scene-boundaries/game.ts
  public/test-scenes/0.90.scene-boundaries/models/PalmTree_01.glb
  public/test-scenes/0.90.scene-boundaries/models/T_Underwater.png
  public/test-scenes/0.90.scene-boundaries/models/shark.gltf
  public/test-scenes/0.90.scene-boundaries/scene.json
  public/test-scenes/0.90.scene-boundaries/tsconfig.json
Labels: ready for review

#461 fix: build deployment dist on pipeline
  .circleci/config.yml
  Makefile
Labels: bug, devexp/qa

#460 fix: show loading screen before teleporting
  packages/unity-interface/dcl.ts
Labels: bug, lifecycle

#465 fix: remove scene ready observer when it corresponds
  packages/shared/world/parcelSceneManager.ts
Labels: bug, lifecycle

#464 fix: drop "entity is already in the engine"
  packages/decentraland-ecs/src/ecs/Engine.ts
Labels: ready for review

#466 fix: silence unity plz
  static/unity/Build/DCLUnityLoader.js
  static/unity/Build/unity.json
Labels: devexp/qa, ready for review

#450 feat: A/B buttons input events
  packages/decentraland-ecs/src/decentraland/Input.ts
  packages/decentraland-ecs/src/decentraland/Types.ts
  packages/engine/entities/SharedSceneContext.ts
  public/test-scenes/-1.-50.basic-interactions/game.ts
  public/test-scenes/-100.109.input-api/game.ts
  public/test-scenes/-100.80.solar-system-comms/game.ts
  public/test-scenes/-102.103.positional-sound/game.ts
Labels: merge me!

#480 feat: add secure radius before scenes are unloaded
  packages/config/index.ts
  packages/decentraland-loader/lifecycle/controllers/parcel.ts
  packages/decentraland-loader/lifecycle/lib/scope.ts
  packages/decentraland-loader/lifecycle/manager.ts
  packages/decentraland-loader/lifecycle/worker.ts
Labels: lifecycle

#481 fix: Auth problems
  package-lock.json
  package.json
  packages/config/index.ts
  packages/shared/auth/Auth.ts
  packages/shared/auth/CommsAuth/index.ts
  packages/shared/auth/Login.ts
  packages/shared/auth/actions.ts
  packages/shared/auth/index.ts
  packages/shared/auth/reducer.ts
  packages/shared/auth/sagas.ts
  packages/shared/auth/selectors.ts
  packages/shared/auth/sha256.ts
  packages/shared/auth/types.ts
  packages/shared/comms/index.ts
  packages/shared/index.ts
  packages/shared/world/profiles.ts
  static/auth/auth0.min.js
  static/auth/env.js
  static/auth/login.html
  static/auth/login.js
  static/auth/login_callback.html
  static/auth/login_callback.js
  static/auth/logout.html
  static/auth/logout.js
  static/auth/logout_callback.html
  static/auth/logout_callback.js
  test/unit/communications.test.tsx
Labels: devexp/qa, ready for review

#492 chore: update unity artifact to 0.7.6
  static/unity/Build/unity.data.unityweb
  static/unity/Build/unity.json
  static/unity/Build/unity.wasm.code.unityweb
  static/unity/Build/unity.wasm.framework.unityweb
Labels: ready for review

#491 fix: logout unauthorized users
  packages/shared/auth/sagas.ts
Labels: bug

#479 chore: implement moving platforms test scene
  public/test-scenes/0.5.moving-platforms/game.ts
  public/test-scenes/0.5.moving-platforms/scene.json
Labels: ready for review

#497 fix: missing preview spawn point
  packages/entryPoints/preview.ts
  packages/unity-interface/dcl.ts
Labels: bug

#496 feat: notifications in Unity
  packages/shared/types.ts
  packages/unity-interface/dcl.ts
Labels: ready for review

#449 feat: Raycast
  packages/decentraland-ecs/src/decentraland/Events.ts
  packages/decentraland-ecs/src/decentraland/Implementation.ts
  packages/decentraland-ecs/src/decentraland/PhysicsCast.ts
  packages/decentraland-ecs/src/decentraland/Systems.ts
  packages/decentraland-ecs/src/decentraland/Types.ts
  packages/decentraland-ecs/src/index.ts
  packages/engine/entities/SharedSceneContext.ts
  packages/scene-system/scene.system.ts
  packages/shared/types.ts
  public/test-scenes/-100.40.raycasting/game.ts
  public/test-scenes/-100.40.raycasting/scene.json
  public/test-scenes/-100.40.raycasting/tsconfig.json
  public/test-scenes/-100.50.raycasting/game.ts
  public/test-scenes/-100.50.raycasting/scene.json
  public/test-scenes/-100.50.raycasting/tsconfig.json
Labels: ready for review

#505 chore: adding hold for stg deployments
  .circleci/config.yml
Labels: devexp/qa

#501 chore: update moving platforms test scene
  public/test-scenes/0.5.moving-platforms/game.ts
Labels: ready for review

#463 fix: cache of compiled scenes
  .circleci/config.yml
  README.md
  public/ecs-scenes/-200,110-relative-layout-ui/game.ts
  public/hell-map/135.127.gnark-patrol/game.ts
Labels: ready for review

#504 chore: refactor teleport flow
  packages/atomicHelpers/parcelScenePositions.ts
  packages/decentraland-loader/lifecycle/controllers/position.ts
  packages/decentraland-loader/lifecycle/worker.ts
  packages/entryPoints/babylon.ts
  packages/entryPoints/preview.ts
  packages/entryPoints/unity.ts
  packages/shared/types.ts
  packages/shared/world/parcelSceneManager.ts
  packages/shared/world/positionThings.ts
  packages/unity-interface/dcl.ts
Labels: lifecycle, ready for review

#509 chore: refactor pipeline
  .circleci/config.yml
  Makefile
  scripts/replaceVersion.ts
  static/index.html
Labels: devexp/qa

#507 chore: update scene boundaries test scene
  public/test-scenes/0.90.scene-boundaries/game.ts
  public/test-scenes/0.90.scene-boundaries/models/Avatar_Idle.glb
  public/test-scenes/0.90.scene-boundaries/models/PalmTree_01.glb
Labels: ready for review

#513 chore: update moving platforms test scene
  public/test-scenes/0.5.moving-platforms/game.ts
Labels: ready for review

#510 proposed: new pipeline
  .circleci/config.yml
Labels: devexp/qa, ready for review

#525 chore: update moving platforms test scene
  public/test-scenes/0.5.moving-platforms/game.ts
Labels: ready for review

#541 fix: text input onchange event
  public/test-scenes/618.618-ui-text-input/game.ts
Labels: merge me!, ready for review

#546 chore: copy unity files to build
  Makefile
Labels: devexp/qa

#540 feat: kernel can enable or disable unity HUDs
  packages/entryPoints/preview.ts
  packages/entryPoints/unity.ts
  packages/shared/types.ts
  packages/unity-interface/dcl.ts
Labels: ready for review
