Repository decentraland/kernel, pull requests merged in 2019-07, with the labels that each got.

#299 fix: audio should not be playing by default
  packages/decentraland-ecs/src/decentraland/Audio.ts
Labels: ready for review

#297 chore: add first version built with Unity 2019
  static/unity/Build/DCLUnityLoader.js
  static/unity/Build/UnityLoader.js
  static/unity/Build/unity.data.unityweb
  static/unity/Build/unity.json
  static/unity/Build/unity.wasm.code.unityweb
  static/unity/Build/unity.wasm.framework.unityweb
Labels: WIP

#314 fix: unity initialization
  packages/entryPoints/unity.ts
Labels: blocked

#316 fix: avatars being destroyed randomly when they shouldn't
  packages/config/index.ts
  packages/decentraland-ecs/src/decentraland/Implementation.ts
  packages/ui/avatar/avatarSystem.ts
Labels: ready for review

#342 fake progress bar
  static/images/progress-logo.png
  static/index.html
  static/unity/Build/DCLUnityLoader.js
Labels: ready for review

#375 fix: exposed 'visible' and 'withCollisions' shape properties
  packages/decentraland-ecs/src/decentraland/Components.ts
Labels: ready for review
