Repository decentraland/kernel, pull requests merged in 2019-10, with the labels that each got.

#554 fix: copy files on make, not postinstall
  Makefile
  package-lock.json
  package.json
Labels: ready for review

#555 chore: update readme with renderer package instructions
  README.md
Labels: merge me!

#562 fix: using tab focus aware timers
  packages/shared/timers/Timer.ts
  packages/shared/timers/index.ts
  packages/shared/world/parcelSceneManager.ts
Labels: bug

#569 fix: replace all occurrences of reg exp
  scripts/replaceVersion.ts
Labels: bug, merge me!

#566 fix: adding phony targets to list
  Makefile
Labels: devexp/qa, merge me!

#567 fix: Now messages are sent in chunks separated by '\n'
  package-lock.json
  package.json
  packages/shared/timers/index.ts
  packages/unity-interface/dcl.ts
Labels: has feedback

#571 fix: persisting own profile as the peer ones
  packages/shared/comms/index.ts
  packages/shared/index.ts
  test/unit/communications.test.tsx
Labels: bug

#577 chore: add non skeletal animations test scene
  public/test-scenes/135.123.shark-animation/game.ts
  public/test-scenes/135.123.shark-animation/scene.json
  public/test-scenes/136.123.non-skeletal-animations/.dclignore
  public/test-scenes/136.123.non-skeletal-animations/game.ts
  public/test-scenes/136.123.non-skeletal-animations/models/All.glb
  public/test-scenes/136.123.non-skeletal-animations/models/Move.glb
  public/test-scenes/136.123.non-skeletal-animations/models/Rotation.glb
  public/test-scenes/136.123.non-skeletal-animations/models/Scale.glb
  public/test-scenes/136.123.non-skeletal-animations/scene.json
Labels: ready for review

#274 feat: builder unity integration
  package-lock.json
  packages/config/index.ts
  packages/decentraland-ecs/src/decentraland/Types.ts
  packages/engine/dcl/index.ts
  packages/entryPoints/editor.ts
  packages/entryPoints/preview.ts
  packages/shared/auth/Auth.ts
  packages/shared/index.ts
  packages/shared/types.ts
  packages/unity-interface/dcl.ts
  packages/unity-interface/initializer.ts
Labels: builder

#587 fix: builder's scene reset
  packages/entryPoints/editor.ts
Labels: merge me!

#585 chore: changing wearable-api endpoint
  packages/config/index.ts
Labels: ready for review

#582 feat: adding user id to identity module
  packages/decentraland-ecs/types/@decentraland/Identity/index.d.ts
  packages/shared/apis/UserIdentity.ts
  packages/shared/types.ts
  public/ecs-scenes/-200.-1-user-data/game.ts
  public/ecs-scenes/-200.-1-user-data/scene.json
  public/ecs-scenes/-200.-1-user-data/tsconfig.json
Labels: merge me!

#584 feat: added call to send the number of new available wearables
  packages/unity-interface/dcl.ts
Labels: merge me!

#580 fix: sending new position to prior position topic when transitioning
  packages/shared/comms/index.ts
  packages/shared/comms/worldInstanceConnection.ts
Labels: ready for review

#599 chore: update client renderer package
  package-lock.json
  package.json
Labels: ready for review

#600 chore: path simulator server
  Makefile
  packages/decentraland-ecs/src/decentraland/Input.ts
  packages/shared/index.ts
  packages/unity-interface/dcl.ts
  scripts/runPathSimulator.ts
Labels: devexp/qa

#608 chore: adding metrics for fatal errors and lifecycle events
  packages/config/index.ts
  packages/entryPoints/unity.ts
  packages/shared/analytics.ts
  packages/shared/auth/sagas.ts
  packages/shared/index.ts
  packages/shared/loading/ReportFatalError.ts
  packages/shared/loading/types.ts
  packages/shared/store/metricSaga.ts
  packages/shared/store/rootSaga.ts
  packages/unity-interface/dcl.ts
  packages/unity-interface/initializer.ts
Labels: ready for review

#614 chore: add irregular shape bounds test scene
  public/test-scenes/2.90.irregular-mesh-boundaries/game.ts
  public/test-scenes/2.90.irregular-mesh-boundaries/models/irregular.glb
  public/test-scenes/2.90.irregular-mesh-boundaries/scene.json
Labels: ready for review

#616 chore: update renderer package version
  package-lock.json
  package.json
Labels: ready for review

#619 fix: minor fix in catalog selectors
  packages/shared/passports/selectors.ts
Labels: bug

#617 chore: copy build on install
  Makefile
Labels: devexp/qa
