Repository decentraland/kernel, pull requests merged in 2019-06, with the labels that each got.

#254 fix: unity teleport
  .gitignore
  packages/unity-interface/dcl.ts
Labels: ready for review

#224 feat: use the new & faster content service endpoint
  Makefile
  packages/decentraland-loader/lifecycle/controllers/download.ts
  packages/decentraland-loader/lifecycle/controllers/scene.ts
  packages/shared/types.ts
  public/local-ipfs/mappings
  scripts/createMockJson.ts
  scripts/runTestServer.ts
  test/testHelpers.ts
Labels: blocked

#256 chore: update unity loading screen style
  static/tetra.html
  static/unity/Build/DCLUnityLoader.js
Labels: ready for review

#265 feat: add segment key for .org
  packages/shared/index.ts
Labels: analytics

#262 chore: update chat scene
  packages/decentraland-ecs/src/decentraland/UIShapes.ts
  packages/ui/avatar/chatWindow.ts
Labels: ready for review

#267 feat: new avatars integration
  packages/decentraland-ecs/src/decentraland/AvatarShape.ts
  packages/decentraland-ecs/src/decentraland/Components.ts
  packages/decentraland-ecs/src/index.ts
  packages/ui/avatar/avatarSystem.ts
  public/test-parcels/40.40.avatar-shape/avatarassets/avatar_maleskinbase.png
  public/test-parcels/40.40.avatar-shape/avatarassets/avatarwearables_tx.png
  public/test-parcels/40.40.avatar-shape/avatarassets/basemale.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/eyebrows_00.png
  public/test-parcels/40.40.avatar-shape/avatarassets/eyebrows_texture.png
  public/test-parcels/40.40.avatar-shape/avatarassets/eyes_00.png
  public/test-parcels/40.40.avatar-shape/avatarassets/eyes_mask.png
  public/test-parcels/40.40.avatar-shape/avatarassets/eyes_texture.png
  public/test-parcels/40.40.avatar-shape/avatarassets/m_eyewear_aviatorstyle.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/m_facialhair_frenchmustache.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/m_feet_greenflipflops.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/m_hair_punk_01.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/m_lbody_greyjoggers.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/m_ubody_greentshirt.glb
  public/test-parcels/40.40.avatar-shape/avatarassets/mouth_00.png
  public/test-parcels/40.40.avatar-shape/avatarassets/mouth_texture.png
  public/test-parcels/40.40.avatar-shape/game.ts
  public/test-parcels/40.40.avatar-shape/scene.json
  static/unity/Build/unity.data.unityweb
  static/unity/Build/unity.wasm.code.unityweb
  static/unity/Build/unity.wasm.framework.unityweb
  test/visualValidation/avatar.test.tsx
  test/visualValidation/skyAndLights.test.tsx
Labels: WIP

#284 feat: filter some events before segment
  packages/shared/analytics.ts
Labels: analytics

#283 feat: allow parenting to null
  packages/decentraland-ecs/src/decentraland/Implementation.ts
  packages/decentraland-ecs/src/ecs/Entity.ts
  packages/decentraland-ecs/src/ecs/IEntity.ts
  test/unit/ecs.test.tsx
Labels: tests
